apiVersion: v1
kind: Service
metadata:
  name: subpython
  labels:
    app: subpython
    role: service
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: subpython