apiVersion: v1
kind: Service
metadata:
  name: sumrust
  labels:
    app: sumrust
    role: service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: default
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: sumrust
    role: service
    tier: backend