apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggscala
spec:
  selector:
    matchLabels:
      app: aggscala
  template:
    metadata:
      labels:
        app: aggscala
    spec:
      containers:
      - name: aggscala
        image: diegopacheco/agg-scala:v1
        env:
          - name: SUB_SERVICE_URL
            value: "http://subpython.default.svc.cluster.local:5000/service/sub"
          - name: MUL_SERVICE_URL
            value: "http://muljava.default.svc.cluster.local:8080/service/mul"
          - name: DIV_SERVICE_URL
            value: "http://divgo.default.svc.cluster.local:6000/service/div"
          - name: SUM_SERVICE_URL
            value: "http://sumrust.default.svc.cluster.local:3000/service/sum"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090