apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggscala
spec:
  selector:
    matchLabels:
      app: aggscala
  template:
    metadata:
      labels:
        app: aggscala
    spec:
      containers:
      - name: aggscala
        image: diegopacheco/agg-scala:v1
        env:
          - name: SUB_SERVICE_URL
            value: "http://sub:5000/service/sub"
          - name: MUL_SERVICE_URL
            value: "http://mul:8080/service/mul"
          - name: DIV_SERVICE_URL
            value: "http://div:6000/service/div"
          - name: SUM_SERVICE_URL
            value: "http://sum:3000/service/sum"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090