apiVersion: v1
kind: Service
metadata:
  name: aggscala
  labels:
    app: aggscala
    role: service
    tier: backend
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: aggscala