apiVersion: v1
kind: Service
metadata:
  name: muljava
  labels:
    app: muljava
    role: service
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: muljava
    role: service
    tier: backend